[package]
name = "lua_runner_wasm"
version = "0.1.0"
edition = "2021"


[dependencies]
mlua = { version = "0.11", features = ["lua54", "vendored"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
